#!usr/bin/env bash

tmux new -s project -d

while [ "$#" -gt 0]; do
    curr=$1
    shift

    case "$curr" in
    "-w")
        tmux new -t website: -n shell -d 'cd $HOME/storage/shared/Codes/website && pipenv shell'
        ;;
    *) echo "Unavailable command... $curr"
    esac
done

